# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to Npmjs

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://registry.npmjs.org/
      - run: |
          if [ -z "$NPM_SCOPE" ]; then
            sed -i '' "s|@utilcode/simple-template|@${{ github.event.repository.name }}|g" package.json
          else
            NPM_SCOPE=${NPM_SCOPE}
            REPOSITORY_NAME=${{github.event.repository.name}}
            REPOSITORY_NAME=${REPOSITORY_NAME##*/}
            sed -i '' "s|@utilcode/simple-template|${{ github.event.repository.name }}|g" package.json
          fi
      - run: sed -i '' "s|@https://github.com/utilcode/simple-template|https://github.com/${{ github.event.repository.name }}|g" package.json
      - run: |
            sed -i '' "s|\"version\": \"[^\"]*\"|\"version\": \"${{ github.event.release.tag_name }}\"|g" package.json
      - run: npm ci
      - run: npm publish --access public --registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
